-- Add 10 attractive properties to Himavarsha account
INSERT INTO public.properties (
  id,
  owner_id,
  title,
  description,
  property_type,
  address,
  location,
  pricing,
  max_guests,
  bedrooms,
  bathrooms,
  amenities,
  images,
  status,
  is_featured,
  rating,
  review_count
) VALUES 
-- 1. Goa Beach Villa
(
  gen_random_uuid(),
  '67af3277-e025-4cca-a504-b4f2d723f7ca',
  'Luxury Goa Beach Villa with Infinity Pool',
  'Experience ultimate luxury at this stunning beachfront villa in North Goa. Wake up to panoramic ocean views, relax by the infinity pool, and enjoy private beach access. Perfect for groups seeking an exclusive coastal retreat with world-class amenities.',
  'villa',
  'Anjuna Beach, North Goa, Goa 403509',
  '{"city": "Goa", "state": "Goa", "country": "India", "latitude": 15.5937, "longitude": 73.7470}',
  '{"currency": "INR", "daily_rate": 45000}',
  16,
  8,
  6,
  ARRAY['Pool', 'Beach Access', 'WiFi', 'Air Conditioning', 'Kitchen', 'Parking', 'Security', 'Housekeeping', 'BBQ Area', 'Spa Services'],
  ARRAY['/src/assets/beachside-paradise.jpg', '/src/assets/sunset-villa-resort.jpg'],
  'approved',
  true,
  4.8,
  127
),
-- 2. Rajasthan Royal Palace
(
  gen_random_uuid(),
  '67af3277-e025-4cca-a504-b4f2d723f7ca',
  'Royal Heritage Palace - Udaipur',
  'Stay like royalty in this magnificent 18th-century palace overlooking Lake Pichola. Featuring authentic Rajasthani architecture, royal suites, and traditional hospitality. An unforgettable experience combining heritage charm with modern luxury.',
  'heritage',
  'City Palace Road, Udaipur, Rajasthan 313001',
  '{"city": "Udaipur", "state": "Rajasthan", "country": "India", "latitude": 24.5854, "longitude": 73.6833}',
  '{"currency": "INR", "daily_rate": 50000}',
  20,
  10,
  8,
  ARRAY['Heritage Architecture', 'Lake View', 'WiFi', 'Air Conditioning', 'Royal Dining', 'Valet Parking', 'Concierge', 'Cultural Programs', 'Spa', 'Butler Service'],
  ARRAY['/src/assets/royal-heritage-villa.jpg'],
  'approved',
  true,
  4.9,
  89
),
-- 3. Kerala Backwater Resort
(
  gen_random_uuid(),
  '67af3277-e025-4cca-a504-b4f2d723f7ca',
  'Kerala Floating Villa - Alleppey Backwaters',
  'Immerse yourself in Kerala backwater serenity at this unique floating villa. Traditional Kerala architecture meets modern comfort. Enjoy houseboat cruises, authentic cuisine, and spectacular sunset views over the tranquil waters.',
  'villa',
  'Vembanad Lake, Alleppey, Kerala 688006',
  '{"city": "Alleppey", "state": "Kerala", "country": "India", "latitude": 9.4981, "longitude": 76.3388}',
  '{"currency": "INR", "daily_rate": 35000}',
  12,
  6,
  4,
  ARRAY['Backwater View', 'Houseboat Access', 'WiFi', 'Air Conditioning', 'Traditional Cuisine', 'Parking', 'Ayurvedic Spa', 'Fishing', 'Cultural Tours', 'Airport Transfer'],
  ARRAY['/src/assets/lakeside-retreat.jpg', '/src/assets/sunset-villa-resort.jpg'],
  'approved',
  true,
  4.7,
  156
),
-- 4. Himachal Mountain Retreat
(
  gen_random_uuid(),
  '67af3277-e025-4cca-a504-b4f2d723f7ca',
  'Himalayan Mountain Retreat - Manali',
  'Escape to this breathtaking mountain retreat with snow-capped Himalayan views. Features cozy wooden interiors, fireplace lounges, and access to adventure sports. Perfect for mountain lovers seeking luxury amidst nature.',
  'cottage',
  'Old Manali Road, Manali, Himachal Pradesh 175131',
  '{"city": "Manali", "state": "Himachal Pradesh", "country": "India", "latitude": 32.2396, "longitude": 77.1887}',
  '{"currency": "INR", "daily_rate": 25000}',
  14,
  7,
  5,
  ARRAY['Mountain View', 'Fireplace', 'WiFi', 'Heating', 'Kitchen', 'Parking', 'Adventure Sports', 'Spa', 'Trekking Guide', 'Bonfire Area'],
  ARRAY['/src/assets/mountain-cottage.jpg'],
  'approved',
  true,
  4.6,
  203
),
-- 5. Mumbai Penthouse
(
  gen_random_uuid(),
  '67af3277-e025-4cca-a504-b4f2d723f7ca',
  'Luxury Mumbai Penthouse - Bandra West',
  'Experience Mumbai urban luxury in this stunning penthouse offering panoramic city and sea views. Features modern amenities, rooftop terrace, and prime location near entertainment districts. Perfect for corporate stays and celebrations.',
  'apartment',
  'Linking Road, Bandra West, Mumbai, Maharashtra 400050',
  '{"city": "Mumbai", "state": "Maharashtra", "country": "India", "latitude": 19.0544, "longitude": 72.8316}',
  '{"currency": "INR", "daily_rate": 40000}',
  10,
  5,
  4,
  ARRAY['City View', 'Sea View', 'WiFi', 'Air Conditioning', 'Modern Kitchen', 'Gym Access', 'Rooftop Terrace', 'Security', 'Elevator', 'Premium Location'],
  ARRAY['/src/assets/sunset-villa-resort.jpg'],
  'approved',
  false,
  4.5,
  78
),
-- 6. Pune Garden Estate
(
  gen_random_uuid(),
  '67af3277-e025-4cca-a504-b4f2d723f7ca',
  'Enchanted Garden Estate - Pune Hills',
  'Discover tranquility at this sprawling garden estate nestled in Pune hills. Beautiful landscaped gardens, event spaces, and peaceful ambiance make it perfect for weddings, retreats, and family gatherings.',
  'estate',
  'Lonavala-Pune Highway, Pune, Maharashtra 411045',
  '{"city": "Pune", "state": "Maharashtra", "country": "India", "latitude": 18.5590, "longitude": 73.7770}',
  '{"currency": "INR", "daily_rate": 30000}',
  25,
  12,
  7,
  ARRAY['Garden View', 'Event Space', 'WiFi', 'Air Conditioning', 'Catering Kitchen', 'Ample Parking', 'Wedding Venue', 'Pool', 'Gazebo', 'Photography Areas'],
  ARRAY['/src/assets/garden-estate.jpg', '/src/assets/farm-house-bliss.jpg'],
  'approved',
  true,
  4.8,
  145
),
-- 7. Bangalore Lake Villa
(
  gen_random_uuid(),
  '67af3277-e025-4cca-a504-b4f2d723f7ca',
  'Serene Lake Villa - Bangalore Outskirts',
  'Unwind at this picturesque lakefront villa just outside Bangalore. Enjoy water activities, peaceful lake views, and modern amenities. Ideal for tech professionals seeking weekend getaways and team retreats.',
  'villa',
  'Hesaraghatta Lake, Bangalore North, Karnataka 560088',
  '{"city": "Bangalore", "state": "Karnataka", "country": "India", "latitude": 13.1358, "longitude": 77.4766}',
  '{"currency": "INR", "daily_rate": 28000}',
  18,
  9,
  6,
  ARRAY['Lake View', 'Water Sports', 'WiFi', 'Air Conditioning', 'Kitchen', 'Parking', 'Boat Access', 'Fishing', 'Conference Room', 'Team Building Activities'],
  ARRAY['/src/assets/lakeside-retreat.jpg'],
  'approved',
  false,
  4.4,
  92
),
-- 8. Udaipur Heritage Haveli
(
  gen_random_uuid(),
  '67af3277-e025-4cca-a504-b4f2d723f7ca',
  'Traditional Rajasthani Haveli - Udaipur',
  'Experience authentic Rajasthani culture in this beautifully restored 200-year-old haveli. Features traditional architecture, courtyards, and royal hospitality. Perfect for cultural enthusiasts and heritage lovers.',
  'heritage',
  'Jagdish Temple Area, Udaipur, Rajasthan 313001',
  '{"city": "Udaipur", "state": "Rajasthan", "country": "India", "latitude": 24.5797, "longitude": 73.6843}',
  '{"currency": "INR", "daily_rate": 32000}',
  15,
  8,
  5,
  ARRAY['Heritage Property', 'Courtyard', 'WiFi', 'Air Conditioning', 'Traditional Decor', 'Cultural Programs', 'Local Cuisine', 'Guided Tours', 'Handicraft Shopping', 'Folk Music'],
  ARRAY['/src/assets/royal-heritage-villa.jpg'],
  'approved',
  false,
  4.7,
  134
),
-- 9. Coorg Coffee Plantation
(
  gen_random_uuid(),
  '67af3277-e025-4cca-a504-b4f2d723f7ca',
  'Coffee Plantation Estate - Coorg',
  'Immerse yourself in aromatic coffee plantations at this charming estate in Coorg. Wake up to misty mornings, enjoy fresh coffee, and explore spice gardens. Perfect for nature lovers and coffee enthusiasts.',
  'estate',
  'Madikeri-Virajpet Road, Coorg, Karnataka 571201',
  '{"city": "Coorg", "state": "Karnataka", "country": "India", "latitude": 12.3375, "longitude": 75.8069}',
  '{"currency": "INR", "daily_rate": 20000}',
  12,
  6,
  4,
  ARRAY['Plantation View', 'Coffee Experience', 'WiFi', 'Fireplace', 'Nature Trails', 'Parking', 'Spice Tours', 'Bird Watching', 'Organic Garden', 'Ayurvedic Treatments'],
  ARRAY['/src/assets/farm-house-bliss.jpg', '/src/assets/garden-estate.jpg'],
  'approved',
  false,
  4.6,
  167
),
-- 10. Alibaug Beach House
(
  gen_random_uuid(),
  '67af3277-e025-4cca-a504-b4f2d723f7ca',
  'Private Beach House - Alibaug',
  'Escape to this exclusive beach house with private beach access in Alibaug. Modern amenities meet coastal charm with infinity pool, beach activities, and stunning sunset views. Perfect for Mumbai weekend getaways.',
  'villa',
  'Awas Beach, Alibaug, Maharashtra 402201',
  '{"city": "Alibaug", "state": "Maharashtra", "country": "India", "latitude": 18.6414, "longitude": 72.8722}',
  '{"currency": "INR", "daily_rate": 38000}',
  16,
  8,
  6,
  ARRAY['Private Beach', 'Beach Activities', 'WiFi', 'Air Conditioning', 'Pool', 'Parking', 'Water Sports', 'BBQ Area', 'Sunset Views', 'Housekeeping'],
  ARRAY['/src/assets/beachside-paradise.jpg', '/src/assets/sunset-villa-resort.jpg'],
  'approved',
  true,
  4.9,
  98
);